name: 'Label timer'
auther: 'Tsubasa MOCHIDA'
runs:
  using: 'docker'
#  image: 'docker://ghcr.io/tbsmcd/label_timer/labeler:v1.9'
  image: 'Docekrfile'
inputs:
  targets:
    description: 'Target labels, comma-separated.'
    required: true
  token:
    description: 'Github access token'
    required: true
  comment:
    description: 'Add comment?(bool)'
    default: true
  sum_time:
    description: 'Calculate the total time?'
    default: true
outputs:
  results:
    description: 'Execution result(json)'
