name: 'Label timer'
auther: 'Tsubasa MOCHIDA'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  targets:
    description: 'Target labels, comma-separated.'
    required: true
  token:
    description: 'Github access token'
    required: true
  comment:
    description: 'Add comment?(bool)'
    default: true

