name: 'Label timer'
author: 'Tsubasa MOCHIDA'
description: 'It measures the amount of time an issue has had a specific label.'
runs:
  using: 'docker'
#  image: "Dockerfile"
  image: 'docker://ghcr.io/tbsmcd/label_timer/labeler:v1.12'
inputs:
  targets:
    description: 'Target labels, comma-separated.'
    required: true
  token:
    description: 'Github access token'
    required: true
  comment:
    description: 'Add comment?(bool)'
    default: true
outputs:
  action:
    description: 'Triggered action'
  label:
    description: 'Target label'
  passed_seconds:
    description: 'Passed seconds'
  sum_seconds:
    description: 'Passed seconds(total)'
