name: 'Label timer'
author: 'Tsubasa MOCHIDA'
description: 'It measures the amount of time an issue has had a specific label.'
branding:
  icon: 'bell'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/tbsmcd/label_timer/labeler:v3.0'
inputs:
  targets:
    description: 'Target labels, comma-separated.'
    required: true
  token:
    description: 'Github access token'
    required: true
outputs:
  passed_seconds:
    description: 'Passed seconds'
  sum_seconds:
    description: 'Passed seconds(total)'
  url:
    description: 'URL of Issue or Pull Request'
