name: Test
on:
  issues:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@master
        with:
          targets:
          - '対応中'
          - '依頼中'
