name: Test
on:
  issues:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@master
        with:
          targets:
            - label: '対応中'
            - label: '依頼中'